### ISSUE TITLE
I Have a sugestion to readme.MD

### ISSUE THREAD

**Issue by ograndebe** [marcel-licence/esp32_usb_midi#12]
If I understood correctly, this repo's purpose is to send midi messages from the microcontroller to a computer via USB.
At first sight, I thought that this code enables receiving midi messages from a Keyboard to a microcontroller via USB.

It would be nice to put this information more explicitly in the readme.MD (from what to what).

I'm opening this issue just trying to help, you make a wonderful job, keep going. 
I'm trying to gather some time to put my hands on your code and make some POCs.

**Comment by marcel-licence** [comment]
Hi,
thank you very much for your feedback. You are right that there is a lot of information missing in my projects.
I did forget to add the information that the USB Host Breakoutboard is required for this project.
In this project some stuff should be removed and linked to the library (there are the same sources). I try to keep the latest code centralized to allow users to gain from bug fixes and new features in all other projects.

So the ESP32 project has two interfaces: USB Host MIDI (allowing to connect a USB MIDI controller to it).
It has its onboard features likes ADC (which can be used to generate control change messages).
You can add a MIDI DIN interface to it with a little circuit (I am not sure if I've implemented MIDI in and out for DIN).
The ESP32 appears as a serial connection at your computer which could be also used to forward MIDI messages, using a tool like hairless MIDI allows the connection to other MIDI specific software.

Hope this helps a bit
