### ISSUE TITLE
Esp32 library was spelled differently for me

### ISSUE THREAD

**Issue by MichaelPNolan** [marcel-licence/esp32_usb_midi#5]
#include <Arduino.h> 
I changed to a cap A in Arduino.h to get it to find the header in the libraries I have which are from

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

Don't know if you should change code but comment perhaps. Also delete this issue if this is silly. I know some others are trying to follow your work and get this to compile so if this helps ...

**Comment by marcel-licence** [comment]
I think I won't be an issue if compiling and execution works =)
Arduino will also add the include by itself if its missing. In the build folder you can see that a automated genrated cpp file will be placed which is the result of putting all ino files together and doing arduino magic

**Comment by MichaelPNolan** [comment]
I tried using 1.0.4 version of ESP32 board libs. I still had to change it to cap A for it to compile. So ... if I make a fork of your code I think ... i'd put it that way. Now that I have the USB throwing up notes from the launchpad on the serial monitor I can start integrating the rest of the hardware and see if this thing rocks.

**Comment by marcel-licence** [comment]
perfect =)

I've checked the generated cpp file. You are fully right the capital letter should be used.

esp32_usb_midi.ino.cpp:
`#include <Arduino.h>
#line 1 "D:\\Workspace\\projects\\public\\esp32_usb_midi\\esp32_usb_midi.ino"
/*
 * pinout of ESP32 DevKit found here:
 * https://circuits4you.com/2018/12/31/esp32-devkit-esp32-wroom-gpio-pinout/
 *
 * Author: Marcel Licence
 */

#include "config.h"

/*
 * required include files
 */
#include <arduino.h>
#include <WiFi.h>

/* this is used to add a task to core 0 */
TaskHandle_t  Core0TaskHnd ;


void setup()
{`

I will fix that on my side. I would guess it is dependend of the arduino version you are using or working on windows or linux. In some case the upper/lower case is ignored. Thanks

**Comment by MichaelPNolan** [comment]
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8

Initialize Synth Module
Initialize I2SHello USBMidi now we can start

Usb init done!

ESP.getFreeHeap() 129528
ESP.getMinFreeHeap() 129508
ESP.getHeapSize() 277148
ESP.getMaxAllocHeap() 69376
Firmware started successfully
state: 32
    USB_ATTACHED_SUBSTATE_SETTLE
voice filter reso: 0.500
main filter reso: 0.500
main filter cutoff: 0.000
delay feedback: 0.000
delay level: 0.000
delay length: 0.000ms
selWaveForm2: 0
selWaveForm: 0
state: 64
    USB_ATTACHED_SUBSTATE_WAIT_RESET_COMPLETE
state: 80
    USB_ATTACHED_SUBSTATE_WAIT_SOF
state: 81
    USB_ATTACHED_SUBSTATE_WAIT_RESET
state: 144
    USB_STATE_RUNNING
VID: 1235, PID: 0036
short: 90 27 7f
short: 90 37 7f
short: 90 37 00
short: 90 27 00
